ALTER TABLE assets ADD COLUMN depreciation_rate NUMERIC(5, 2) DEFAULT 0.00;
ALTER TABLE assets ADD COLUMN disposal_date DATE;
ALTER TABLE assets DROP CONSTRAINT IF EXISTS assets_status_check;
ALTER TABLE assets ADD CONSTRAINT assets_status_check CHECK (status IN ('AVAILABLE','ALLOCATED','UNDER_MAINTENANCE','DAMAGED','LOST','RETIRED','DISPOSED'));
