package com.assetmgmt.service;

import com.assetmgmt.dto.AuthDto;
import com.assetmgmt.entity.User;
import com.assetmgmt.exception.BusinessException;
import com.assetmgmt.repository.RoleRepository;
import com.assetmgmt.repository.UserRepository;
import com.assetmgmt.security.JwtUtil;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

@Service
public class AuthService {

    private final AuthenticationManager authenticationManager;
    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final JwtUtil jwtUtil;
    private final PasswordEncoder passwordEncoder;
    private final EmailService emailService;

    public AuthService(AuthenticationManager authenticationManager,
                       UserRepository userRepository,
                       RoleRepository roleRepository,
                       JwtUtil jwtUtil,
                       PasswordEncoder passwordEncoder,
                       EmailService emailService) {
        this.authenticationManager = authenticationManager;
        this.userRepository = userRepository;
        this.roleRepository = roleRepository;
        this.jwtUtil = jwtUtil;
        this.passwordEncoder = passwordEncoder;
        this.emailService = emailService;
    }

    public AuthDto.LoginResponse login(AuthDto.LoginRequest request) {
        User user = userRepository.findByUsername(request.getUsername())
                .orElseThrow(() -> new BusinessException("User not found"));
        if (!user.isEnabled()) {
            throw new BusinessException("Your account is deactivated. Please contact the administrator.");
        }

        authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(request.getUsername(), request.getPassword())
        );
        
        String token = jwtUtil.generateToken(user);
        
        java.util.List<String> roles = user.getRoles().stream()
                .map(com.assetmgmt.entity.Role::getName)
                .collect(java.util.stream.Collectors.toList());
                
        java.util.List<String> permissions = user.getRoles().stream()
                .flatMap(r -> r.getPermissions().stream())
                .map(com.assetmgmt.entity.Permission::getName)
                .distinct()
                .collect(java.util.stream.Collectors.toList());

        return AuthDto.LoginResponse.builder()
                .token(token)
                .type("Bearer")
                .id(user.getId())
                .username(user.getUsername())
                .email(user.getEmail())
                .fullName(user.getFullName())
                .roles(roles)
                .permissions(permissions)
                .passwordResetRequired(user.isPasswordResetRequired())
                .build();
    }

    public AuthDto.UserDto createUser(AuthDto.CreateUserRequest request) {
        if (userRepository.existsByUsername(request.getUsername())) {
            throw new BusinessException("Username already taken: " + request.getUsername());
        }
        if (userRepository.existsByEmail(request.getEmail())) {
            throw new BusinessException("Email already in use: " + request.getEmail());
        }
        
        com.assetmgmt.entity.Role role = roleRepository.findByName(request.getRole())
                .orElseThrow(() -> new BusinessException("Role not found: " + request.getRole()));

        String rawPassword = request.getPassword();
        boolean isAutoGenerated = false;
        if (rawPassword == null || rawPassword.trim().isEmpty()) {
            rawPassword = generateRandomPassword();
            isAutoGenerated = true;
        }

        User user = User.builder()
                .username(request.getUsername())
                .password(passwordEncoder.encode(rawPassword))
                .email(request.getEmail())
                .fullName(request.getFullName())
                .roles(new java.util.HashSet<>(java.util.List.of(role)))
                .enabled(true)
                .passwordResetRequired(isAutoGenerated)
                .build();

        User savedUser = userRepository.save(user);

        if (isAutoGenerated) {
            emailService.sendWelcomeEmail(savedUser.getEmail(), "http://localhost:4200/login", savedUser.getUsername(), rawPassword);
        }

        return AuthDto.UserDto.fromUser(savedUser);
    }

    private String generateRandomPassword() {
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*";
        java.security.SecureRandom random = new java.security.SecureRandom();
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 10; i++) {
            sb.append(chars.charAt(random.nextInt(chars.length())));
        }
        return sb.toString();
    }
}
